#!/usr/bin/env php
<?php
// 定义项目路径
define('ROOT_PATH', dirname(dirname(__DIR__)) . '/');
define('APP_PATH', dirname(dirname(__DIR__)) . '/application/');
// 加载框架引导文件
require ROOT_PATH.'thinkphp/console.php';