<?php

return array (
  'name' => '超管，欢迎回来',
  'beian' => '',
  'cdnurl' => '',
  'version' => '1.0.2',
  'timezone' => 'Asia/Shanghai',
  'forbiddenip' => '',
  'languages' => 
  array (
    'backend' => 'zh-cn',
    'frontend' => 'zh-cn',
  ),
  'fixedpage' => 'dashboard',
  'categorytype' => 
  array (
    'default' => 'Default',
    'page' => 'Page',
    'article' => 'Article',
    'test' => 'Test',
  ),
  'configgroup' => 
  array (
    'basic' => 'Basic',
    'email' => 'Email',
    'dictionary' => 'Dictionary',
    'user' => 'User',
    'example' => 'Example',
  ),
  'mail_type' => '1',
  'mail_smtp_host' => 'smtp.qq.com',
  'mail_smtp_port' => '465',
  'mail_smtp_user' => '10000',
  'mail_smtp_pass' => 'password',
  'mail_verify_type' => '2',
  'mail_from' => '10000@qq.com',
  'zcc' => '10',
  'tvideo' => '10',
  'ggg' => '<p style="widows: 1; line-height: 1.2;"><b style="color: rgb(0, 51, 153); font-family: &quot;sans serif&quot;, tahoma, verdana, helvetica; font-size: 16px;">欢迎来到月色TV！</b></p><p style="widows: 1; line-height: 1.2;"><span style="font-family: &quot;sans serif&quot;, tahoma, verdana, helvetica; font-weight: bold; font-size: 14px; color: rgb(255, 156, 0);">温馨提示：</span></p><p style="widows: 1; line-height: 1.2;"><span style="color: rgb(34, 34, 34); font-family: Consolas, &quot;Lucida Console&quot;, &quot;Courier New&quot;, monospace; font-size: 12px; white-space: pre-wrap;">播放或者充值方面有問題可以聯繫我們的在线客服！</span><span style="color: rgb(255, 255, 255); font-family: &quot;sans serif&quot;, tahoma, verdana, helvetica; font-size: 12px; font-weight: 700;">。</span></p><p style="widows: 1; line-height: 1.2;"><span style="font-family: &quot;sans serif&quot;, tahoma, verdana, helvetica; font-size: 18px; font-weight: bold;">​</span><span style="font-family: Consolas, &quot;Lucida Console&quot;, &quot;Courier New&quot;, monospace; font-size: 14px; white-space: pre-wrap;"><b style=""><span style="color: rgb(255, 156, 0);">提示:</span><span style="color: rgb(34, 34, 34);">&nbsp;</span></b></span></p><p style="widows: 1; line-height: 1.2;"><span style="color: rgb(34, 34, 34); font-family: Consolas, &quot;Lucida Console&quot;, &quot;Courier New&quot;, monospace; font-size: 12px; white-space: pre-wrap; widows: 2;">1.只需要充值一次後即可享受無限次數試看。</span></p><p style="widows: 1; line-height: 1.2;"><span style="color: rgb(34, 34, 34); font-family: Consolas, &quot;Lucida Console&quot;, &quot;Courier New&quot;, monospace; font-size: 12px; white-space: pre-wrap; widows: 2;">2.已經付費的視頻可以在個人中心-購買記錄裡無限次數無限時間免費播放。</span></p><p style="widows: 1; line-height: 1.2;"><span style="font-family: Consolas, &quot;Lucida Console&quot;, &quot;Courier New&quot;, monospace; white-space: pre-wrap; widows: 2;"><span style="color: rgb(34, 34, 34); font-size: 12px;">請牢記永久回家地址：</span><span style="font-size: 14px; background-color: rgb(255, 255, 255); color: rgb(255, 0, 0);"><b style="">ystv18.com</b></span></span><span style="color: rgb(34, 34, 34); font-family: Consolas, &quot;Lucida Console&quot;, &quot;Courier New&quot;, monospace; font-size: 12px; white-space: pre-wrap;"><br></span></p><p style="widows: 1; line-height: 1.2;"><span style="font-size: 10px;">﻿</span></p>',
  'fxlj' => '月色TV，一款你值得留恋的APP:http://app.ystv18.com/',
  'integral_one' => '0',
  'integral_two' => '100',
  'integral_three' => '200',
  'rebate_one' => '5',
  'rebate_two' => '8',
  'rebate_three' => '15',
  'agent_one' => '20%',
  'agent_two' => '30%',
  'agent_three' => '50%',
  'gdt' => '欢迎来到葡萄宝盒！如在购买会员过程中遇到问题，请联系在线客服！',
  'allowfree' => '1',
  'pay' => '0',
  'website' => 'http://app.ystv18.com',
  'direct' => '温馨提示：月色TV不提供任何线下见面和交友活动，添加联系方式为私人行为，出现任何情况与本平台无关。',
  'video_prefix' => '',
  'chat' => 'http://app.ystv18.com/kefu/php/app.php?widget-mobile',
  'auto_comment' => '0',
);